CREATE TABLE MEMBER(
    NICK VARCHAR2(50) PRIMARY KEY, //글자수 너무 적어서 사이즈 키움
    PW VARCHAR2(20)
);

CREATE TABLE SAVE(
    NICK VARCHAR2(20) PRIMARY KEY, //1개의 닉네임당 1개파일만 세이브 가능, 프라이머리 키
    STAGE_NUM NUMBER(3,0),
    SCORE NUMBER,
    CONSTRAINT FK_NICK FOREIGN KEY(NICK) REFERENCES MEMBER(NICK)
);

CREATE TABLE RANKING(
    RANK_ID NUMBER PRIMARY KEY, //중복값 불가, 데이터별 구분 위한 번호
    NICK VARCHAR2(20),
    SCORE NUMBER,
    ENDTIME DATE,
    CONSTRAINT FK_RANKNICK FOREIGN KEY(NICK) REFERENCES MEMBER(NICK)
);

CREATE SEQUENCE rank_seq
START WITH 1      -- 1부터 시작
INCREMENT BY 1    -- 1씩 증가
NOCACHE           -- 캐시 없이 실행 (생략 가능)
NOCYCLE;          -- 최대값에 도달해도 다시 1로 초기화되지 않음
