CREATE TABLE TB_MEMBER(
    NICK VARCHAR2(50) PRIMARY KEY,
    PW VARCHAR2(20) NOT NULL
);

CREATE TABLE TB_SAVE(
    NICK VARCHAR2(50) PRIMARY KEY,
    STAGE_NUM NUMBER(3,0),
    SCORE NUMBER,
    CONSTRAINT FK_NICK FOREIGN KEY(NICK) REFERENCES TB_MEMBER(NICK)
);

CREATE TABLE TB_RANKING(
    RANK_ID NUMBER PRIMARY KEY,
    NICK VARCHAR2(50),
    SCORE NUMBER,
    ENDTIME DATE,
    CONSTRAINT FK_RANKNICK FOREIGN KEY(NICK) REFERENCES TB_MEMBER(NICK)
);

//시퀀스 사용해서 랭킹에 중복없이 번호 부여 
CREATE SEQUENCE rank_seq
START WITH 1      -- 1부터 시작
INCREMENT BY 1    -- 1씩 증가
NOCACHE           -- 캐시 없이 실행 (생략 가능)
NOCYCLE;          -- 최대값에 도달해도 다시 1로 초기화되지 않음
