CREATE TABLE MEMBER(
    NICK VARCHAR2(50) PRIMARY KEY,
    PW VARCHAR2(20)
);

CREATE TABLE SAVE(
    NICK VARCHAR2(20) PRIMARY KEY, //1개의 닉네임당 1개파일만 세이브 가능, 프라이머리 키
    STAGE_NUM NUMBER(3,0),
    SCORE NUMBER,
    CONSTRAINT FK_NICK FOREIGN KEY(NICK) REFERENCES MEMBER(NICK)
);

CREATE TABLE RANKING(
    RANK_ID NUMBER PRIMARY KEY, //중복값 불가, 데이터별 구분 위한 번호
    NICK VARCHAR2(20),
    SCORE NUMBER,
    ENDTIME DATE,
    CONSTRAINT FK_RANKNICK FOREIGN KEY(NICK) REFERENCES MEMBER(NICK)
);

