CREATE TABLE MEMBER(
    NICK VARCHAR2(20) PRIMARY KEY,
    PW VARCHAR2(20)
);

CREATE TABLE SAVE(
    NICK VARCHAR2(20),
    STAGE_NUM NUMBER(3,0),
    SCORE NUMBER,
    CONSTRAINT FK_NICK FOREIGN KEY(NICK) REFERENCES MEMBER(NICK)
);

CREATE TABLE RANKING(
    NICK VARCHAR2(20),
    SCORE NUMBER,
    ENDTIME DATE,
    CONSTRAINT FK_RANKNICK FOREIGN KEY(NICK) REFERENCES MEMBER(NICK)
);

